import type {
  DataSource,
  QualityCheck,
  QuarantinedRecord,
  Anomaly,
  SLAItem,
  Recommendation,
  KnowledgeBaseItem,
  Resolution,
  Feedback,
  DashboardSummary,
  TimeSeriesData,
  ReviewItem,
} from "../types";

// Dashboard Summary
export const mockDashboardSummary: DashboardSummary = {
  totalRecordsProcessed: 1245678,
  dataQualityPassRate: 96.8,
  openAnomalies: 23,
  slaBreaches: 3,
  avgResolutionTime: 4.2,
};

// Time Series Data for Anomaly Trends
export const mockAnomalyTrends: TimeSeriesData[] = [
  { date: "2026-08-01", value: 15 },
  { date: "2026-08-02", value: 12 },
  { date: "2026-08-03", value: 18 },
  { date: "2026-08-04", value: 14 },
  { date: "2026-08-05", value: 22 },
  { date: "2026-08-06", value: 19 },
  { date: "2026-08-07", value: 16 },
  { date: "2026-08-08", value: 20 },
  { date: "2026-08-09", value: 17 },
  { date: "2026-08-10", value: 23 },
  { date: "2026-08-11", value: 21 },
  { date: "2026-08-12", value: 18 },
  { date: "2026-08-13", value: 25 },
  { date: "2026-08-14", value: 19 },
];

// Anomaly Severity Breakdown
export const mockSeverityBreakdown: TimeSeriesData[] = [
  { date: "Critical", value: 5, category: "severity" },
  { date: "High", value: 12, category: "severity" },
  { date: "Medium", value: 28, category: "severity" },
  { date: "Low", value: 15, category: "severity" },
];

// Data Sources
export const mockDataSources: DataSource[] = [
  {
    id: "src-001",
    name: "Claims Data Feed",
    type: "Claims",
    subType: "PDF/CSV/EDI/EHR",
    recordCount: 458920,
    lastSync: "2026-08-20T10:15:00Z",
    status: "healthy",
    errorCount: 12,
    ingestionRate: 1250,
    description: "Primary claims data from multiple sources including PDF, CSV, EDI, and EHR integrations",
  },
  {
    id: "src-002",
    name: "Prescriber Database",
    type: "Prescriber",
    subType: "NPI/Specialty/License",
    recordCount: 125450,
    lastSync: "2026-08-20T09:30:00Z",
    status: "healthy",
    errorCount: 3,
    ingestionRate: 85,
    description: "Prescriber information including NPI numbers, specialties, and license verification",
  },
  {
    id: "src-003",
    name: "Pharmacy Network",
    type: "Pharmacy",
    subType: "NDC/Drug/Fill Info",
    recordCount: 892340,
    lastSync: "2026-08-20T10:45:00Z",
    status: "warning",
    errorCount: 45,
    ingestionRate: 2100,
    description: "Pharmacy data with NDC codes, drug information, and prescription fill details",
  },
  {
    id: "src-004",
    name: "Authorization System",
    type: "Authorization",
    subType: "Pre-auth/Referrals/Approvals",
    recordCount: 234560,
    lastSync: "2026-08-20T08:20:00Z",
    status: "error",
    errorCount: 128,
    ingestionRate: 320,
    description: "Prior authorization requests, referrals, and approval workflows",
  },
];

// Quality Checks
export const mockQualityChecks: QualityCheck[] = [
  {
    id: "qc-001",
    name: "Claims Schema Validation",
    type: "Schema Validation",
    recordsChecked: 458920,
    recordsFailed: 2340,
    passPercentage: 99.49,
    lastRun: "2026-08-20T10:00:00Z",
    status: "pass",
    description: "Validates claims records against defined schema",
  },
  {
    id: "qc-002",
    name: "Member ID Completeness",
    type: "Completeness Check",
    recordsChecked: 458920,
    recordsFailed: 890,
    passPercentage: 99.81,
    lastRun: "2026-08-20T10:05:00Z",
    status: "pass",
  },
  {
    id: "qc-003",
    name: "Claim Number Uniqueness",
    type: "Uniqueness Check",
    recordsChecked: 458920,
    recordsFailed: 45,
    passPercentage: 99.99,
    lastRun: "2026-08-20T10:10:00Z",
    status: "pass",
  },
  {
    id: "qc-004",
    name: "Prescriber NPI Reference",
    type: "Referential Integrity",
    recordsChecked: 458920,
    recordsFailed: 5670,
    passPercentage: 98.76,
    lastRun: "2026-08-20T10:15:00Z",
    status: "warning",
  },
  {
    id: "qc-005",
    name: "Claim Amount Business Rules",
    type: "Business Rule Check",
    recordsChecked: 458920,
    recordsFailed: 12340,
    passPercentage: 97.31,
    lastRun: "2026-08-20T10:20:00Z",
    status: "warning",
  },
  {
    id: "qc-006",
    name: "Pharmacy NDC Validation",
    type: "Schema Validation",
    recordsChecked: 892340,
    recordsFailed: 8920,
    passPercentage: 99.00,
    lastRun: "2026-08-20T10:45:00Z",
    status: "pass",
  },
  {
    id: "qc-007",
    name: "Authorization Date Completeness",
    type: "Completeness Check",
    recordsChecked: 234560,
    recordsFailed: 15680,
    passPercentage: 93.31,
    lastRun: "2026-08-20T08:20:00Z",
    status: "fail",
  },
];

// Quarantined Records
export const mockQuarantinedRecords: QuarantinedRecord[] = [
  {
    id: "qr-001",
    recordId: "CLM-2026-089234",
    sourceTable: "claims",
    sourceType: "Claims",
    failReason: "Missing required field: member_id",
    checkType: "Completeness Check",
    quarantinedAt: "2026-08-20T09:15:00Z",
    data: {
      claim_number: "CLM-2026-089234",
      service_date: "2026-08-15",
      provider_npi: "1234567890",
      claim_amount: 250.00,
    },
  },
  {
    id: "qr-002",
    recordId: "CLM-2026-089456",
    sourceTable: "claims",
    sourceType: "Claims",
    failReason: "Invalid NPI reference - Prescriber not found",
    checkType: "Referential Integrity",
    quarantinedAt: "2026-08-20T09:20:00Z",
  },
  {
    id: "qr-003",
    recordId: "AUTH-2026-045678",
    sourceTable: "authorizations",
    sourceType: "Authorization",
    failReason: "Authorization effective date is null",
    checkType: "Completeness Check",
    quarantinedAt: "2026-08-20T08:25:00Z",
  },
];

// Anomalies
export const mockAnomalies: Anomaly[] = [
  {
    id: "anom-001",
    source: "Claims Data Feed",
    anomalyType: "Duplicate Claims Spike",
    severityScore: 92,
    detectedTime: "2026-08-20T07:30:00Z",
    status: "open",
    affectedRecords: 1250,
    description: "Unusual spike in duplicate claim submissions detected",
    rootCause: "EDI file processing error causing duplicate record ingestion from HealthCare Partner X",
    impactAnalysis: {
      affectedClaimsCount: 1250,
      estimatedVolumeImpact: 125000,
      downstreamSystems: ["Payment Processing", "Provider Portal", "Member Portal"],
      businessImpact: "Potential duplicate payments and member confusion",
      financialImpact: 312500,
    },
  },
  {
    id: "anom-002",
    source: "Prescriber Database",
    anomalyType: "Missing NPI Data",
    severityScore: 76,
    detectedTime: "2026-08-19T15:20:00Z",
    status: "investigating",
    affectedRecords: 340,
    description: "Batch of prescriber records missing NPI validation",
    rootCause: "API timeout from external NPI validation service",
    impactAnalysis: {
      affectedClaimsCount: 340,
      estimatedVolumeImpact: 51000,
      downstreamSystems: ["Claims Adjudication", "Provider Network"],
      businessImpact: "Claims cannot be processed without valid NPI",
    },
  },
  {
    id: "anom-003",
    source: "Pharmacy Network",
    anomalyType: "NDC Code Mismatch",
    severityScore: 58,
    detectedTime: "2026-08-19T11:45:00Z",
    status: "investigating",
    affectedRecords: 890,
    description: "NDC codes not matching FDA drug database",
    rootCause: "Pharmacy system using outdated NDC code reference table",
  },
  {
    id: "anom-004",
    source: "Authorization System",
    anomalyType: "Approval Workflow Timeout",
    severityScore: 85,
    detectedTime: "2026-08-20T06:10:00Z",
    status: "open",
    affectedRecords: 567,
    description: "Authorization approval workflow timing out",
    rootCause: "Database connection pool exhaustion in authorization service",
    impactAnalysis: {
      affectedClaimsCount: 567,
      estimatedVolumeImpact: 85050,
      downstreamSystems: ["Member Services", "Provider Portal"],
      businessImpact: "Delayed authorizations impacting patient care",
    },
  },
  {
    id: "anom-005",
    source: "Claims Data Feed",
    anomalyType: "Data Format Inconsistency",
    severityScore: 45,
    detectedTime: "2026-08-18T14:30:00Z",
    status: "resolved",
    affectedRecords: 234,
    description: "Date format inconsistency in claim submission",
  },
];

// SLA Items
export const mockSLAItems: SLAItem[] = [
  {
    id: "sla-001",
    title: "Duplicate Claims Spike - Claims Data Feed",
    priority: "High",
    slaHours: 4,
    detectedTime: "2026-08-20T07:30:00Z",
    estimatedResolutionTime: 2.5,
    status: "at_risk",
    assignedTo: "Sarah Johnson",
    source: "Claims Data Feed",
  },
  {
    id: "sla-002",
    title: "Approval Workflow Timeout - Authorization System",
    priority: "High",
    slaHours: 4,
    detectedTime: "2026-08-20T06:10:00Z",
    estimatedResolutionTime: 3.0,
    status: "breached",
    assignedTo: "Mike Chen",
    source: "Authorization System",
  },
  {
    id: "sla-003",
    title: "Missing NPI Data - Prescriber Database",
    priority: "Medium",
    slaHours: 8,
    detectedTime: "2026-08-19T15:20:00Z",
    estimatedResolutionTime: 4.5,
    status: "on_track",
    assignedTo: "Emily Rodriguez",
    source: "Prescriber Database",
  },
  {
    id: "sla-004",
    title: "NDC Code Mismatch - Pharmacy Network",
    priority: "Medium",
    slaHours: 8,
    detectedTime: "2026-08-19T11:45:00Z",
    estimatedResolutionTime: 5.0,
    status: "on_track",
    assignedTo: "David Kim",
    source: "Pharmacy Network",
  },
  {
    id: "sla-005",
    title: "Schema Validation Errors - Claims",
    priority: "Low",
    slaHours: 24,
    detectedTime: "2026-08-19T09:00:00Z",
    estimatedResolutionTime: 6.0,
    status: "on_track",
    assignedTo: "Lisa Martinez",
    source: "Claims Data Feed",
  },
];

// Recommendations
export const mockRecommendations: Recommendation[] = [
  {
    id: "rec-001",
    anomalyId: "anom-001",
    actionType: "Reprocess",
    description: "Stop current ingestion, deduplicate records, and reprocess claims batch",
    confidence: 95,
    relevanceScore: 98,
    sopReference: "SOP-CLAIMS-004: Duplicate Record Handling",
    estimatedEffort: "2-3 hours",
    steps: [
      "Halt EDI file ingestion from HealthCare Partner X",
      "Identify and flag duplicate records using claim_number + service_date",
      "Deduplicate records keeping the earliest submission",
      "Resume ingestion with corrected data feed",
      "Validate no duplicates remain in processed batch",
    ],
  },
  {
    id: "rec-002",
    anomalyId: "anom-002",
    actionType: "Contact Team",
    description: "Escalate to external NPI validation service provider",
    confidence: 88,
    relevanceScore: 92,
    sopReference: "SOP-PRESCRIBER-002: NPI Validation Escalation",
    estimatedEffort: "1-2 hours",
    steps: [
      "Contact NPI validation service support team",
      "Provide affected prescriber IDs and timestamp range",
      "Request immediate service restoration",
      "Implement retry mechanism for failed validations",
    ],
  },
  {
    id: "rec-003",
    anomalyId: "anom-003",
    actionType: "Fix Data",
    description: "Update pharmacy NDC code reference table",
    confidence: 92,
    relevanceScore: 90,
    sopReference: "SOP-PHARMACY-003: NDC Reference Updates",
    estimatedEffort: "3-4 hours",
    steps: [
      "Download latest NDC database from FDA",
      "Run comparison script against current pharmacy table",
      "Generate update SQL script for mismatched codes",
      "Apply updates in staging environment",
      "Validate and promote to production",
    ],
  },
  {
    id: "rec-004",
    anomalyId: "anom-004",
    actionType: "Escalate",
    description: "Emergency database connection pool expansion",
    confidence: 96,
    relevanceScore: 99,
    sopReference: "SOP-AUTH-001: Emergency Performance Response",
    estimatedEffort: "30 minutes",
    steps: [
      "Increase database connection pool size from 50 to 100",
      "Restart authorization service pods",
      "Monitor connection pool metrics",
      "Reprocess failed authorization requests",
    ],
  },
];

// Knowledge Base
export const mockKnowledgeBase: KnowledgeBaseItem[] = [
  {
    id: "kb-001",
    title: "Duplicate Record Handling Process",
    category: "SOP",
    content: "Standard procedure for handling duplicate records in claims processing...",
    tags: ["claims", "duplicates", "data-quality"],
    lastUpdated: "2026-07-15T10:00:00Z",
    relevanceCount: 45,
  },
  {
    id: "kb-002",
    title: "NPI Validation Service Integration",
    category: "SOP",
    content: "Guidelines for integrating with external NPI validation services...",
    tags: ["prescriber", "npi", "validation"],
    lastUpdated: "2026-06-20T14:30:00Z",
    relevanceCount: 32,
  },
  {
    id: "kb-003",
    title: "Maximum Claim Amount Business Rule",
    category: "Business Rule",
    content: "Claims exceeding $50,000 require additional manual review...",
    tags: ["claims", "business-rules", "validation"],
    lastUpdated: "2026-08-01T09:15:00Z",
    relevanceCount: 28,
  },
  {
    id: "kb-004",
    title: "EDI Processing Error - Nov 2025",
    category: "Past Resolution",
    content: "Resolution steps for EDI duplicate processing error encountered in November 2025...",
    tags: ["claims", "edi", "resolution"],
    lastUpdated: "2025-11-18T16:45:00Z",
    relevanceCount: 18,
  },
  {
    id: "kb-005",
    title: "Authorization SLA Policy",
    category: "Policy",
    content: "Prior authorizations must be processed within 4 business hours...",
    tags: ["authorization", "sla", "policy"],
    lastUpdated: "2026-05-10T11:00:00Z",
    relevanceCount: 52,
  },
];

// Resolutions
export const mockResolutions: Resolution[] = [
  {
    id: "res-001",
    anomalyId: "anom-001",
    status: "in_progress",
    actionType: "Reprocess Claims",
    assignedTo: "Sarah Johnson",
    startTime: "2026-08-20T08:00:00Z",
    notes: [
      "EDI ingestion halted at 08:05",
      "Identified 1,250 duplicate records",
      "Deduplication script running",
    ],
    slaDeadline: "2026-08-20T11:30:00Z",
  },
  {
    id: "res-002",
    anomalyId: "anom-002",
    status: "in_progress",
    actionType: "Escalate/Contact Team",
    assignedTo: "Emily Rodriguez",
    startTime: "2026-08-19T16:00:00Z",
    notes: [
      "Ticket opened with NPI validation service provider",
      "Service restored at 18:30",
      "Retry mechanism implemented",
    ],
    slaDeadline: "2026-08-19T23:20:00Z",
  },
  {
    id: "res-003",
    anomalyId: "anom-004",
    status: "pending",
    actionType: "Fix Data",
    assignedTo: "Mike Chen",
    notes: ["Awaiting approval to increase connection pool"],
    slaDeadline: "2026-08-20T10:10:00Z",
  },
  {
    id: "res-004",
    anomalyId: "anom-005",
    status: "completed",
    actionType: "Fix Data",
    assignedTo: "David Kim",
    startTime: "2026-08-18T15:00:00Z",
    completedTime: "2026-08-18T17:30:00Z",
    notes: [
      "Standardized date format across all claims sources",
      "Applied transformation rule to ETL pipeline",
      "Validated 100% of affected records",
    ],
    slaDeadline: "2026-08-19T14:30:00Z",
  },
];

// Feedback
export const mockFeedback: Feedback[] = [
  {
    id: "fb-001",
    anomalyId: "anom-005",
    recommendationId: "rec-003",
    wasHelpful: true,
    comments: "The recommended fix worked perfectly. Clear steps and accurate time estimate.",
    submittedBy: "David Kim",
    submittedAt: "2026-08-18T17:45:00Z",
    category: "Recommendation Quality",
  },
  {
    id: "fb-002",
    anomalyId: "anom-002",
    recommendationId: "rec-002",
    wasHelpful: true,
    comments: "Good escalation path, but SOP reference could include contact details.",
    suggestedImprovement: "Add direct contact information for NPI service support team to SOP",
    submittedBy: "Emily Rodriguez",
    submittedAt: "2026-08-19T19:00:00Z",
    category: "Rule Improvement",
  },
  {
    id: "fb-003",
    anomalyId: "anom-003",
    wasHelpful: false,
    comments: "Anomaly was a false positive - NDC codes were actually correct, reference data was outdated.",
    submittedBy: "Lisa Martinez",
    submittedAt: "2026-08-19T13:20:00Z",
    category: "False Positive",
  },
];

// Review Items
export const mockReviewItems: ReviewItem[] = [
  {
    id: "rev-001",
    anomaly: mockAnomalies[0],
    recommendation: mockRecommendations[0],
    status: "pending_review",
  },
  {
    id: "rev-002",
    anomaly: mockAnomalies[1],
    recommendation: mockRecommendations[1],
    status: "pending_review",
  },
  {
    id: "rev-003",
    anomaly: mockAnomalies[3],
    recommendation: mockRecommendations[3],
    status: "pending_review",
  },
];
